// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB753OlmLIV-ZwxzfXcJj1-OdN59nakaao',
    appId: '1:70626312389:web:e5e72f1c9e106ff027f0ac',
    messagingSenderId: '70626312389',
    projectId: 'test-bf718',
    authDomain: 'test-bf718.firebaseapp.com',
    databaseURL: 'https://test-bf718-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test-bf718.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOyN4CLvyMl5rHgssA5FJ7dcBYJ1XWeS4',
    appId: '1:70626312389:android:045b52d20fc27fc927f0ac',
    messagingSenderId: '70626312389',
    projectId: 'test-bf718',
    databaseURL: 'https://test-bf718-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test-bf718.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbTisQx-F6l6XhBDX4wMUkAVLz6ner0B4',
    appId: '1:70626312389:ios:c239d38a715068cc27f0ac',
    messagingSenderId: '70626312389',
    projectId: 'test-bf718',
    databaseURL: 'https://test-bf718-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test-bf718.appspot.com',
    iosClientId: '70626312389-vr1iblgn10l09n8pbjo02lqkbk02oq3v.apps.googleusercontent.com',
    iosBundleId: 'com.example.plantmonitoringsystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbTisQx-F6l6XhBDX4wMUkAVLz6ner0B4',
    appId: '1:70626312389:ios:c239d38a715068cc27f0ac',
    messagingSenderId: '70626312389',
    projectId: 'test-bf718',
    databaseURL: 'https://test-bf718-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test-bf718.appspot.com',
    iosClientId: '70626312389-vr1iblgn10l09n8pbjo02lqkbk02oq3v.apps.googleusercontent.com',
    iosBundleId: 'com.example.plantmonitoringsystem',
  );
}
